#!/usr/bin/env python3
import argparse
import binascii
import ctypes
import datetime
import logging
import os
import serial
import serial.threaded
import serial.serialutil as su
import struct
import subprocess as sp
import time
import timeit
import xmodem

from threading import Thread

logging.basicConfig(
    level=logging.DEBUG,
)


class SocatException(Exception):
    pass


# TODO: Make this more usable, to debug failure in connection, also: handle raw data!
class DebugSerial(serial.Serial):
    def __init__(self, *args, **kwargs):
        super(DebugSerial, self).__init__(*args, **kwargs)
        self._filename = datetime.datetime.now().strftime("debug.%d%m%Y-%H%M%S")

    def read(self, *args, **kwargs):
        ret = super(DebugSerial, self).read(*args, **kwargs)
        self.output_debug(ret)
        return ret

    def write(self, data):
        ret = super(DebugSerial, self).write(data)
        self.output_debug(data)
        return ret

    def output_debug(self, msg):
        with open("{}.hex".format(self._filename), "a") as fh:
            fh.write("{}".format("".join(["{:02X}".format(b) for b in msg])))


class DataReceiver(object):
    def __init__(self, port, location, output_dir,
                 debug=False, preamble=True, preamble_timeout=120):
        self._debug = debug
        self._dir = output_dir
        self._port = port
        self._preamble = preamble
        self._preamble_timeout = preamble_timeout
        self._ttyloc = location

        if not os.path.exists(self._dir):
            raise DataReceiverConfigurationError("{} doesn't exist".format(self._dir))

        self._socat = sp.Popen('socat pty,link={},raw tcp-listen:{},fork,reuseaddr'.format(self._ttyloc, self._port),
                            shell=True)

        time.sleep(1)

        self._thread = Thread(target=self.run)
        self._thread.start()

        self._intentional_exit = False

    def run(self):
        ser_port = None

        try:
            while True:
                logging.info('Waiting for connection on {}...'.format(self._port))
                filename = None
                file_length = 0
                chunk = 0
                total_chunks = 0

                if not ser_port or not ser_port.is_open:
                    cls = serial.Serial
                    if self._debug:
                        cls = DebugSerial
                    ser_port = cls(self._ttyloc,
                                   baudrate=19200,
                                   bytesize=serial.EIGHTBITS,
                                   parity=serial.PARITY_NONE,
                                   stopbits=serial.STOPBITS_ONE,
                                   # TODO: Set in line with configuration of clients
                                   timeout=120,
#                                   write_timeout=10,
                                   rtscts=True,
                                   dsrdtr=True
                                   )
                logging.info('Connected to fake serial {}'.format(self._ttyloc))
                ser_port.flushInput()

                # TODO: If we get a repeated FILENAME request this needs handling in place of the metadata message
                data = None
                filename_command = ""

                while not filename_command.endswith("FILENAME"):
                    data = ser_port.read(size=1)

                    if data:
                        #logging.debug("Data received: {}".format(data))
                        if data.decode("latin-1") == "@":
                            ser_port.write("A".encode("latin-1"))
                        filename_command += data.decode("latin-1")
                        filename_command = filename_command.strip()

                logging.debug("Sending FILENAME response...")
                ser_port.flushInput()
                ser_port.flushOutput()
                ser_port.write("GOFORIT".encode("latin-1"))

                if self._preamble:
                    logging.info("Waiting for filename information...")

                    data = None
                    while not data or (len(data) and data[0] != 0x1a):
                        if data:
                            logging.warning("Redundant character received: {}".
                                            format(hex(ord(data[0]))))
                        data = ser_port.read(size=1)

                    st = time.time()

                    while data[-1] != 0x1b:
                        data += ser_port.read(size=1)
                        if time.time() - st > float(self._preamble_timeout):
                            raise RuntimeError("Preamble timeout has exceeded "
                                               "{} seconds".format(
                                                self._preamble_timeout))

                    try:
                        (lead, length) = struct.unpack_from("BB", data)
                        logging.debug("{}: {}".format(struct.calcsize("BB"), length))

                        # FIXME 2021: why read more, we already have everything?
                        # data += ser_port.read(size=(length + 17))
                        # if data[-1] != 0x1b:
                        #    logging.warning("Possibly malformed header
                        #    message: {}")
                            
                        (filename) = struct.unpack_from("{}s".format(length), data, struct.calcsize("BB"))[0]

                        logging.debug("{}: {}".format(struct.calcsize("=BB{}s".format(length)), filename))
                        (file_length) = struct.unpack_from("<i", data, struct.calcsize("=BB{}s".format(length)))[0]

                        logging.debug("{}: {}".format(struct.calcsize("=BB{}si".format(length)), file_length))
                        (chunk) = struct.unpack_from("<i", data, struct.calcsize("=BB{}si".format(length)))[0]

                        logging.debug("{}: {}".format(struct.calcsize("=BB{}sii".format(length)), chunk))
                        (total_chunks) = struct.unpack_from("<i", data, struct.calcsize("=BB{}sii".format(length)))[0]

                        # TODO: pyremotenode needs to mimic the int32 signed CRC as I don't think I can force
                        # the VM2 to send an unsigned int

                        logging.debug("{}: {}".format(struct.calcsize("=BB{}siii".format(length)), total_chunks))
                        (crc32, tail) = struct.unpack_from("<iB", data,
                                                           struct.calcsize("=BB{}siii".format(length)))
                    except struct.error:
                        raise

                    logging.info("Received filename information, checking...")
                    logging.debug("Filename: {}".format(filename))
                    logging.debug("Filename length: {}".format(length))
                    logging.debug("Filename chunk: {} of {}".format(chunk, total_chunks))
                    logging.debug("File length: {} bytes".format(file_length))
                    logging.debug("Filename CRC: {}".format(crc32))

                    if lead == 0x1a \
                        and ctypes.c_int(binascii.crc32(filename) & 0xffffffff).value == crc32:
                        ser_port.write("NAMERECV\r\n".encode("latin-1"))
                        output_filename = "{}.{}".format(os.path.basename(filename.decode()), chunk)
                    else:
                        raise RuntimeError("Message not consistent")
                else:
                    dt = datetime.datetime.now().strftime("%d%m%Y-%H%M%S")
                    output_filename = "xraw.{}.dat".format(dt)

                def _getc(size, timeout=ser_port.timeout):
                    ser_port.timeout = timeout
                    read = ser_port.read(size=size) or None
                    return read

                def _putc(data, timeout=ser_port.write_timeout):
                    logging.debug("WRITE DATA: {}".format(data))
                    #ser_port.write_timeout = timeout
                    size = ser_port.write(data=data)
                    ser_port.flush()
                    return size

                # TODO: Solve this timeliness to start
                time.sleep(2)
                xfer = xmodem.XMODEM(_getc, _putc)
                with open(os.path.join(self._dir, output_filename), "wb") as fh:
                    xfer.recv(fh, retry=100)

                if self._preamble and filename and chunk == total_chunks:
                    cb = 0

                    with open(os.path.join(self._dir, filename.decode()), "wb") as ofh:
                        done_length = 0

                        for i in range(1, total_chunks+1):
                            chunk_file = os.path.join(self._dir,
                                                   "{}.{}".format(os.path.basename(filename.decode()), chunk))
                            chunk_length = os.stat(chunk_file).st_size
                            logging.debug("Reading chunk {}: {} bytes".format(chunk_file, chunk_length))

                            with open(chunk_file, "rb") as rfh:
                                if chunk_length + done_length > file_length:
                                    read_length = file_length - done_length
                                    logging.info("Only grabbing {} bytes from chunk #{} as it's the remainder".format(
                                        read_length, i
                                    ))
                                else:
                                    read_length = chunk_length

                                logging.debug("Writing {} bytes to {}".format(read_length, os.path.join(self._dir, filename.decode())))
                                ofh.write(rfh.read(read_length))
                logging.info("Done")
            else:
                logging.warning("Invalid message received, looping for another listen")
        finally:
            if ser_port is not None and ser_port.is_open:
                ser_port.close()

            try:
                self._socat.terminate()
            except:
                logging.warning("Could not close the socat process, it's either dead or being a mong...")

    @property
    def debug(self):
        return self._debug

    @debug.setter
    def debug(self, val=True):
        self._debug = val

    @property
    def thread(self):
        return self._thread


class DataReceiverConfigurationError(Exception):
    pass


class DataReceiverRuntimeError(Exception):
    pass

if __name__ == '__main__':
    a = argparse.ArgumentParser()
    a.add_argument("-d", "--debug", help="Write a transaction log", action="store_true", default=False)
    a.add_argument("-n", "--no-preamble", dest="preamble", help="Disable the preamble header message, files will be stored raw", action="store_false", default=True)
    a.add_argument("port", help="TCP port to listen on", type=int)
    a.add_argument("ptyLocation", help="pty to feed TCP to")
    a.add_argument("directory", help="Output directory")
    cmd_args = a.parse_args()

    dm = DataReceiver(cmd_args.port, cmd_args.ptyLocation, cmd_args.directory, 
            debug=cmd_args.debug,
            preamble=cmd_args.preamble)
    dm.thread.join()
    logging.info("Stopped listening for data...")
